### ISSUE TITLE
node-gyp/python requirement during npm install

### ISSUE THREAD

**Issue by gbenthomas** [SoCreate/angular-playground#213] opened 2019-10-12 17:51 UTC
### Versions
6.0.3+

### Repro steps
Without python installed:
`ng new test-angular`
`cd test-angular`
`npm install angular-playground`

### Observed Behavior
```
PS C:\workspaces\samples\test-angular> npm install angular-playground

> weak-napi@1.0.3 install C:\workspaces\samples\test-angular\node_modules\weak-napi
> node-gyp rebuild


C:\workspaces\samples\test-angular\node_modules\weak-napi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\workspaces\samples\test-angular\node_modules\weak-napi
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN jest-image-snapshot@2.11.0 requires a peer of jest@>=20 <=24 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\angular-playground\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! Maximum call stack size exceeded
```

### Desired Behavior
```
Installation should succeed without python (as it did before 6.0.3)
```

### Any other details that may be useful (optional)
I believe this is caused by the update to jest packages. 

Thanks for your time and support!

**Comment by timstoddard** [comment] 2019-10-12 17:56
Hi @gbenthomas, it looks like node-gyp is unable to find python in your path. (`Error: Can't find Python executable "python", you can set the PYTHON env variable.`)

Have you tried reinstalling python, and checking that the python env variable is set?

**Comment by gbenthomas** [comment] 2019-10-12 18:03
Hi @timstoddard, I actually don't have python installed. My point was that python is a new requirement since 6.0.3. It worked fine with 6.0.2. Is there any way to keep the same behavior as before? This will require updates to our CI pipeline as well in order to install python. 

Ideally, we would like to depend on a prebuilt binary instead of building the native modules ourselves (especially since this is used in an Angular project and none of the other npm packages have a native dependency like this).

It's not urgent for us since we can stay on 6.0.2 for now but it would be very appreciated if we could install it without a native dependency!

**Comment by timstoddard** [comment] 2019-10-12 18:21
6.0.3 included updating several of our dependencies to the latest version. The requirement to have python installed comes from node-gyp, which is not one of our direct dependencies. I would recommend filing an issue with the node-gyp repo asking if it's possible to install it without python, as they will know more about it than I.

Closing since issue this is not caused by Playground.

**Closed by timstoddard** 2019-10-12 18:21 UTC

**Comment by timstoddard** [comment] 2019-10-16 23:25
Hey @gbenthomas, just wanted to reach out since we found what we think is the best way to work around this issue. Basically, there's no way to solve this without installing Python and MS build tools. The steps are as follows:
- install python and add it to path
- install latest version of ms build tools
- run the command: `npm config set msvs_version 2019`
