### ISSUE TITLE
Ability to toggle on 'Documentation & Source' Panel

### ISSUE THREAD

**Issue by jamesbuettner** [SoCreate/angular-playground#174] opened 2019-04-13 17:41 UTC
### Desired Behavior
```
It would be nice to have the ability to toggle on a 'Documentation & Source' Panel for people that are developing components for others use.
I would envision it would be able to be toggled on like the 'Overlay'. 
Once toggled on, another floating button above the 'Menu' would appear. Once clicked, a slide-out similar to the 'Component Selector' would appear from the bottom left (to avoid covering up the 'Menu' and 'Documentation & Source' buttons).
Once it appears, it would have two tabs at the top, one for 'Documentation' and one for 'Source'. If no documentation is present, it wouldn't have a tab available (for tab layout, maybe something similar to PrimeNG (https://www.primefaces.org/primeng/#/menubar).
I would envision the source is always pulled from the component template and typescript files, so it could always be available if the feature is toggled on.
```

**Comment by JustinCouto** [comment] 2019-04-14 14:34
Hi There,

This is a really good idea and it is something we have considered.  The things we are unsure about is where you would store the documentation.  Would you create some sort of doc file in your source control next to your sandbox file?  Should your documentation be mixed in with your code and would people want this? Would you want documentation for your frontend and your backend in different places? These are questions we considering when we decided holdoff on this.  We currently use Atlassian's Confluence for documentation.  We built an iFrame widget that allows you to embed your sandboxes right into a Confluence page.  It works pretty well for us. It also allows us to keep all of our documentation in one place. With that being said, this idea sounds nice as well.  I will discuss it with the team and see what there thoughts are. Thanks for submitting it.

**Comment by 13bitts** [comment] 2019-04-14 14:53
Great. All great questions.
Maybe the documentation piece could be deferred? Our use case for Angular Playground may be a bit different, as we are moving towards it for our UI Component Library. The most common theme we see is developers wanting to know what the source is to create the component they see in there application.
Let me know how I can help after you have discussed it.
Thanks.

**Comment by jamesbuettner** [comment] 2019-04-14 19:22
Took a bit and mocked up a view that I thought would be unobtrusive, but if someone wanted to view the source code, it would be available. Icons are wrong and not fully fleshed out, but you should get the idea.
![source-view](https://user-images.githubusercontent.com/4565176/56097982-27c26700-5ec9-11e9-891e-8363aaa8a7a6.png)

**Comment by jamesbuettner** [comment] 2019-04-15 00:26
Apologies for another comment, but I thought a little bit more about various uses that I have seen others ask for. If Plug-In's are something that is desired, having a structured fly-out from the side would enable stacking various 'Plug-In' features without altering the simplicity and ease of use of the initial component switcher/viewer.
The following are a couple variations of what it could look like...
![menu-flyout-closed](https://user-images.githubusercontent.com/4565176/56101512-6d475a00-5ef2-11e9-808a-6c1ec2b66966.png)
![menu-flyout](https://user-images.githubusercontent.com/4565176/56101513-720c0e00-5ef2-11e9-9aff-c257a8b1488e.png)
![menu-flyout-source](https://user-images.githubusercontent.com/4565176/56101514-746e6800-5ef2-11e9-9807-471b1e67718a.png)

The other question you had about how to structure the documentation. 
Where to put the source for documentation?
 - Could this be similar to how Angular does it? You could have it where you can put it right in the Sandbox file, or have a 'documentationUrl' which would link it to the 'documentation.html' for that component. 

Would you want documentation for your frontend and your backend in different places?
 - I think this maybe a case by case basis depending on the team. The documentation I was referring to would be more about the UI Component documentation, which may only be needed when using Playground for a UI Library type resource, but if its optional, everyone can decide for themselves. The documentation plug-in could even just take a URL and pull it in (opposite the way you are currently doing it).

**Comment by JustinCouto** [comment] 2019-04-17 02:49
Thanks for putting the effort into this.  I will discuss it with my team and we will figure out how we want to move forward on this.

**Comment by jamesbuettner** [comment] 2019-04-18 01:07
Perfect. Let me know how I can help.

**Comment by jamesbuettner** [comment] 2019-04-24 15:51
@JustinCouto, have you had a chance to discuss this?

**Comment by JustinCouto** [comment] 2019-04-24 15:56
Hi James, 

We have been discussing it.  There are some issues in how we would exclude certain content from a tabbed code view.  The issue is that there is content in Sand Boxes and possibly components, that you wouldn't want to display in the code view.  We are discussing the best ways to not include this content.  We really like the idea of it, but we need more time to consider the best way of doing it.  We are also always open to proposals or pull requests.  

Thank you,

**Comment by jamesbuettner** [comment] 2019-04-24 23:05
Thanks for the update. 
I was going to start implementing it, but per contributing guidelines, I am hesitant to start if there is little chance of integration. From what I gather, there is interest, just may need small changes.
Is that correct?

**Comment by jamesbuettner** [comment] 2019-05-04 15:46
Following your Contributions guide, getting 403 pushing branch. Can I get access to create the PR?

**Comment by timstoddard** [comment] 2019-05-07 03:46
Hi @jamesbuettner, did you fork the repo before making changes and pushing your branch? We have it set up so you can't just clone this repository and push that way, you need to fork it to your Github account and push the branch from there.

**Comment by timstoddard** [comment] 2019-06-06 18:15
Hey @jamesbuettner, did you have a chance to try the steps I gave in my previous comment? Are you still interested in submitting a PR to Playground?

**Comment by arroyocode** [comment] 2019-07-20 00:27
@jamesbuettner Following up if you're still interested in submitting a PR via fork from your own Github account?

**Comment by arroyocode** [comment] 2019-07-22 16:00
Hiya @jamesbuettner . We've reached out a few times to confirm your interest in submitting a PR and haven't been able to connect with you so we're closing this issue. Thank you for your interest in Angular Playground and the dialog in this issue.

**Closed by arroyocode** 2019-07-22 16:00 UTC
Labels: not planned, request for info
